### PR TITLE
Fix percentage of variability reported to be explained by PCs

### PR DESCRIPTION
**Pull request by nathansam**
The percentage of variability reported to be explained by PCs was previously hard coded in the text, and was off by a couple of percent. This PR fixes this behaviour and should ensure if the percentages reported in the summary output change, so does the text discussing it.

### CODE REVIEW

**Comment by Alanocallaghan** [comment]
The diff on this shows as the entire Rmd but I assume you didn't edit much beyond the %ages? https://github.com/carpentries-incubator/high-dimensional-stats-r/commit/be3dda63663e5abc033c9f1df956f15ed6e17f4f

**Comment by Alanocallaghan** [comment]
Ah seems to just be EOL stuff https://stackoverflow.com/questions/19593909/git-diff-sees-whole-file-as-changed-when-its-not

**Comment by nathansam** [comment]
I was confused why the diff showed the whole file 😅 . This is all that I changed 

https://github.com/nathansam/high-dimensional-stats-r/blob/cf12ad2430329d13b8ec1782093daa35c62e6bdf/_episodes_rmd/05-principal-component-analysis.Rmd#L356-L366

**Comment by nathansam** [comment]
Ultimately I think it is an Rstudio + Windows + non-Windows device interaction. Reverting the change and making the change in VS Code instead resulted in only the lines I actually changed being in the diff.

**Comment by Alanocallaghan** [comment]
I suspect Rstudio might be involved but not sure about windows, as I assume you're doing these edits on mac? Either way lgtm and tyvm

**Pull request merged**
