### PR TITLE
qplot suggestion

### PR DESCRIPTION
**Pull request by ewallace**
Hello,
Here are some suggestions focused around using qplot (and data frames) as default plot.

That is because:
- I never use base plot and find the syntax confusing, maybe learners also
- ggplot2 seems to be overkill as that's not the core lesson material
- qplot is a good compromise with consistent syntax and low overheads on learners
- I think it simplifies the code, and builds a bridge to the places where the lesson needs to use ggplot2

So far I've only tried on episodes 1 and 2. And added a callout explaining the approach to episode 1:

> ## Plotting in this lesson: base R compared to ggplot2
> 
> There are different ways to plot data in R, either base graphics or the
> popular and flexible [ggplot2 package](https://ggplot2.tidyverse.org).
> In this workshop, we mostly use [`qplot`](https://ggplot2.tidyverse.org/reference/qplot.html) 
> as a "quick plot" in ggplot2 that has a consistent interface to make nice graphs.
> Sometimes we use base graphics when there are built-in methods available,
> for example `pairs()`, the `plot()` method for linear models that returns
> diagnostic plots, and for heatmaps the 
> [ComplexHeatmap package](https://bioconductor.org/packages/release/bioc/html/ComplexHeatmap.html).
> 
> You can use the plotting approach that you prefer - don't forget help 
> pages, for example type `?qplot` for how to use qplot.
{: .callout}

Also in episode 1 I made some of the simulated data more data-framey and less matrix-y, which reflects my practice and works with qplot but others' mileage may vary.

Of course I don't mind what's kept and what isn't - just hoping that there's something helpful here?

Relevant to this comment from @hannesbecher : https://github.com/carpentries-incubator/high-dimensional-stats-r/issues/52#issuecomment-1047012434

### CODE REVIEW

**Review by hannesbecher — COMMENTED** [review]
This code is not visible to the course participants. 
Does this code produce the same plot?

**Review by hannesbecher — COMMENTED** [review]
Rather than modifying this code, I would suggest to drop the section on clusters altogether. I think it is not clear what is the point of this exercise and it is not needed here.

**Review by hannesbecher — APPROVED** [review]

**Comment by catavallejos** [comment]
Thanks @ewallace - Because this is a relatively big change that may affect several episodes (it would be god to be consistent with which plotting tool we use), I suggest we do not yet implement this in the master branch. Instead, we can include this as a proposed change within the document that we plan to circulate with our curriculum advisory board. Current draft is available [here](https://hackmd.io/u9vwRANCTTi0S-SkEU99Xg)

**Comment by catavallejos** [comment]
Also, as @hannesbecher said, our planned edits include the removal of the clustering part. Instead, we will provide an overview of the course and the different types of approaches.

**Comment by ewallace** [comment]
Thank you @catavallejos - that sounds great, how can I help? Would it help if I spent an hour suggesting qplot-ification of other episodes? Or something else?

**Comment by ewallace** [comment]
> Also, as @hannesbecher said, our planned edits include the removal of the clustering part. Instead, we will provide an overview of the course and the different types of approaches.

Is the clustering part in intro being removed or (partially) moved to the clustering episode? I think it makes an important point that is aligned to the "Believing in clusters" section. But this comment from me probably belongs in another issue or document.

**Comment by hannesbecher** [comment]
qplot is now deprecated. I suggest we don't merge this now.

**Comment by ewallace** [comment]
Unfortunately @hannesbecher I fear you are right.

**Pull request closed without merging**
