### PR TITLE
Fixed typos and boxes

### PR DESCRIPTION
**Pull request by hannesbecher**
* fixed code typos
* fixed several call-out and challenge boxes
* Added placeholders for glossary and instructor notes.

### CODE REVIEW

**Comment by catavallejos** [comment]
List of suggested changes for "Regression with many outcomes" episode:

- Edit caption for “plot of chunk plot-lm-methyl1” (just before the paragraph starting w/ “For this feature, we can see that …”). Change it to be “A scatter plot of age versus the methylation level for an arbitrarily selected CpG side (the one stored as the first column of `methyl_mat`). Each dot represents an individual”. 
- In “Fitting a linear model” section, expand explanation to say we arbitrarily select the 1st CpG for illustration purposes. Here is the suggested text: “For each CpG, we can fit this model and ger more information from the model object. For illustration purposes, here we arbitrarily select the first CpG in the `methyl_mat` matrix (the one on its first row).” 
- In the solution to Challenge 2, we currently say: “Also, regardless of the p-value, it is unlikely to be a reliable finding, …”. I don’t think that “reliable” is the best term here: the value of the intercept itself is not very meaningful, but why is its estimate not reliable? Suggested edit: “… However, this is not a particularly noteworthy finding, regardless of the p-value! Indeed, we do not have any observations with age zero (nor even any with age < 20).”
- “How does hypothesis testing for a linear model work?” The plot is illustrating the p-value for a 1-sided test. However, the test reported by the summary of lm is a 2-sided test. If you were to calculate the shaded area (which we can; ` 1-pt(0.888, df = 37-2)`), you would get p-value/2 (i.e. 0.19 in this case). Instead, the p-value for the 2-sided test is twice the shaded area (this is corrected in the call-out box below). Perhaps we can change the plot to be a 2-sided one and move it to the call-out box? I can then update the text accordingly. 

[REST IS TBC - I NEED TO CATCH UP THE BUS NOW!]

**Comment by catavallejos** [comment]
List of suggested changes for "Regularised regression" episode:

- There is an error in the code chunk within the "Correlated features – common in high-dimensional data" call-out box (there is a `col` variable that has not been defined). 
-

**Comment by catavallejos** [comment]
Hi @hannesbecher apologies for all the spam today!

All of your changes look good. I also made a few (mostly minor) edits to episodes 1, 2 and 3. One recurrent team across episodes is that we are missing captions (and alternative captions) for the figures. I fixed this on the first 3 episodes. If you could do this for the remaining episodes, I'd be grateful! I can review once you are ready.

**Review by ailithewing — APPROVED** [review]

**Review by ailithewing — APPROVED** [review]

**Comment by ailithewing** [comment]
@catavallejos Are we ready to merge this?

**Comment by catavallejos** [comment]
Hi @ailithewing , yes, I think this is ready to merge now. Sorry I missed it.

**Pull request merged**
