### PR TITLE
Updates to PCA

### PR DESCRIPTION
**Pull request by ailithewing**
Hi Alan,

I've made edits to PCA, mainly wording and attempts to improve flow.

Ailith

### CODE REVIEW

**Comment by Alanocallaghan** [comment]
Argh, somehow this entire file is a merge conflict. I don't know how that happens

**Comment by ailithewing** [comment]
I thought it looked weird. I have no idea how that happened either.

**Comment by Alanocallaghan** [comment]
Ah, hide whitespace changes makes it legible at least

**Comment by Alanocallaghan** [comment]
Usually I would stubbornly try to figure out the git commands to make this a clean merge but instead I've just copied the edits to the current version I've got in my branch. I may re-review at some point as I caught a couple of small typos myself (and I keep doing the same in my own episodes)

**Pull request closed without merging**
