### PR TITLE
remove optional lessons, renumber, clear to enable rebuild

### PR DESCRIPTION
**Pull request by ailithewing**
I've removed the optional lessons, renumbered the remaining lessons and I've removed duplicate lesson numbers from the _episodes directory so that the ordering doesn't get confused when the site builds.

I checked this locally so new ordering should work.

### CODE REVIEW

**Comment by ailithewing** [comment]
I meant to say, I created a new branch hds_main-development that has the current full version of the course in including optional lessons.

**Comment by ailithewing** [comment]
Ah ok, I think this should be fine as I manually removed the legacy .md files that are generated from when the .Rmd files are built...

**Comment by Alanocallaghan** [comment]
That is also how I tried to handle it, and I was surprised by the result, which I was why I remarked - but something may have changed since.

**Review by catavallejos — APPROVED** [review]

**Comment by Alanocallaghan** [comment]
Yeah this doesn't actually end up removing the (R)md files from gh-pages unfortunately, see: https://carpentries-incubator.github.io/high-dimensional-stats-r/ )

See #79

**Pull request merged**
