### PR TITLE
Beta status

### PR DESCRIPTION
**Pull request by ewallace**
The lesson has already been delivered multiple times so suggesting upgrade to beta status.

Or at least to alpha?

### CODE REVIEW

**Comment by catavallejos** [comment]
Hi @ewallace. We are still implementing several edits to the materials: just finished with a round of minor fixes, but expect to do some broader *structural* changes to some of the episodes within the next month or so (some of which were suggested by our curriculum advisory board). Therefore, it's probably best not to upgrade the status yet.

**Comment by catavallejos** [comment]
actually, after reading [here](https://cdh.carpentries.org/the-lesson-life-cycle.html) I think we should upgrade to alpha. However, not ready to be beta yet.

**Review by catavallejos — CHANGES_REQUESTED** [review]

**Comment by ailithewing** [comment]
@ewallace @catavallejos @mallewellyn 
I think by the end of the ed-dash extension we could upgrade to beta or even stable based on the lifecycle above.... what do you think? and how do we do this?

**Comment by alanocallaghan** [comment]
Desperately need to fix the infra/upgrade to the new carpentries infra before this could be called stable

**Comment by ailithewing** [comment]
It's in our plans for the Ed-DaSH extension. As you seem to be working on this pro-bono it would be great if we could have a quick catch up so that we can keep you in the loop with what's going on. I'll drop you an email....

**Pull request merged**
