### PR TITLE
Changes to hierachical clustering

### PR DESCRIPTION
**Pull request by hannesbecher**
* Have split out into a separate section the highlighting of branches in dendrograms
* Have generated crescent-shaped point clouds to show the effect of different linkage methods (Challenge 3)

See my rendered version here https://hannesbecher.github.io/high-dimensional-stats-r/07-hierarchical/index.html

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

### CODE REVIEW

**Comment by hannesbecher** [comment]
Ready for your review whenever you have time, @catavallejos

**Comment by catavallejos** [comment]
Comments that are not about the new edits:

- Line 46 in hierarchical.Rmd: change "features" to "characteristics"

**Comment by catavallejos** [comment]
Hi @hannesbecher sorry it has taken me long to review. I haven't really gone through the final episode before, so I am doing a full pass and adding a few comments/suggestions as I go. I will let you know when ready for your review.

**Comment by catavallejos** [comment]
Hi @hannesbecher I am done with my review. Let me know if there is anything that you would like to discuss.

**Comment by catavallejos** [comment]
Thanks @hannesbecher! Let me know when is ready for review.

**Comment by hannesbecher** [comment]
I've worked on your suggestions, @catavallejos Shall we talk tomorrow?

**Comment by hannesbecher** [comment]
Ready now!Sent from a phone On 22 Feb 2023, at 13:02, Catalina Vallejos ***@***.***> wrote:﻿
Thanks @hannesbecher! Let me know when is ready for review.

**Comment by hannesbecher** [comment]
Hi @catavallejos this is ready for your review. I have not added a callout (which would have been redundant with material already present in episodes 6 and 7). But I have added stuff on linkage methods and a note on clustering not being trivial etc. in episode 7.

Happy to make further changes. Specific suggestions appreciated!

Rendered version here: https://hannesbecher.github.io/high-dimensional-stats-r/07-hierarchical/index.html

**Review by catavallejos — APPROVED** [review]

**Comment by catavallejos** [comment]
Thanks @hannesbecher. The final changes look good, I will let the Carpentries team know that this is ready for review.

**Pull request merged**
